export const PAYMENT_COMMUNICATION_EVENT_TYPES = [
  'PAYMENT_FAILED',
  'PAYMENT_RECOVERED',
  'SUBSCRIPTION_CONFIRMED',
  'SUBSCRIPTION_CANCELLED',
  'ADMIN_OUTREACH',
] as const;

export const PAYMENT_COMMUNICATION_STATUS_TYPES = [
  'PENDING_FOLLOW_UP',
  'RESOLVED',
  'NOT_REQUIRED',
] as const;

export type PaymentEventType = (typeof PAYMENT_COMMUNICATION_EVENT_TYPES)[number];
export type PaymentLogStatus = (typeof PAYMENT_COMMUNICATION_STATUS_TYPES)[number];

export const PAYMENT_COMMUNICATION_OPTIONS = {
  eventTypes: PAYMENT_COMMUNICATION_EVENT_TYPES,
  statuses: PAYMENT_COMMUNICATION_STATUS_TYPES,
};
